### ISSUE TITLE
pycurl.error after restarting download

### ISSUE THREAD

**Issue by frafra** [lmacken/liveusb-creator#31]
When I restart the download, I see a pycurl.error and the progress bar is stuck on "Starting".

```
$ sudo liveusb-creator
file:///usr/lib64/qt5/qml/QtQuick/Controls/ComboBox.qml:513:5: QML Menu: Binding loop detected for property ""
https://download.fedoraproject.org/pub/fedora/linux/releases/23/Workstation/x86_64/iso/Fedora-Live-Workstation-x86_64-23-10.iso
https://download.fedoraproject.org/pub/fedora/linux/releases/23/Workstation/x86_64/iso/Fedora-Live-Workstation-x86_64-23-10.iso
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/liveusb/gui.py", line 88, in run
    iso = self.grabber.urlgrab(self.progress.release.url, reget='simple')
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1172, in urlgrab
    return self._retry(opts, retryfunc, url, filename)
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1064, in _retry
    r = apply(func, (opts,) + args, {})
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1157, in retryfunc
    fo = PyCurlFileObject(url, filename, opts)
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1259, in __init__
    self._do_open()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1598, in _do_open
    self._set_opts()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1385, in _set_opts
    self.curl_obj.setopt(pycurl.NOPROGRESS, False)
pycurl.error: cannot invoke setopt() - perform() is currently running
$ rpm -q liveusb-creator
liveusb-creator-3.15.0-0.1.newui.20151102git857190d6.fc23.noarch
```

**Comment by MartinBriza** [comment]
Closed by 71ab5355f4d70fe90435756773efceb6e74e48dd
