### ISSUE TITLE
^C breaks the program (without closing it)

### ISSUE THREAD

**Issue by frafra** [lmacken/liveusb-creator#32]
When I try to close liveusb-creator using CTRL+C, it doesn't close, but it stops to work properly.
Some examples:

```
$ sudo liveusb-creator
file:///usr/lib64/qt5/qml/QtQuick/Controls/ComboBox.qml:513:5: QML Menu: Binding loop detected for property ""
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/liveusb/gui.py", line 880, in currentImage
    @pyqtProperty(Release, notify=currentImageChanged)
KeyboardInterrupt
qrc:/components/ImageDetails.qml:51: TypeError: Cannot call method 'get' of null
```

```
$ sudo liveusb-creator
file:///usr/lib64/qt5/qml/QtQuick/Controls/ComboBox.qml:513:5: QML Menu: Binding loop detected for property ""
https://download.fedoraproject.org/pub/fedora/linux/releases/23/Workstation/x86_64/iso/Fedora-Live-Workstation-x86_64-23-10.iso
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/liveusb/gui.py", line 880, in currentImage
    @pyqtProperty(Release, notify=currentImageChanged)
KeyboardInterrupt
qrc:/components/DownloadDialog.qml:153: TypeError: Cannot read property 'download' of null
```

**Comment by MartinBriza** [comment]
Yeah, this happens but it seems it's done intentionally for some reason. I'll probably put this annoyance away some time.
