### ISSUE TITLE
Crash triggered around status window

### ISSUE THREAD

**Issue by frantisekz** [lmacken/liveusb-creator#45]
I was able to trigger a crash while playing with window showing download status and flash drives. Cannot reproduce atm.

```
file:///usr/lib64/qt5/qml/QtQuick/Controls/ComboBox.qml:560:5: QML Menu: Binding loop detected for property "__selectedIndex"
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/liveusb/gui.py", line 92, in run
    iso = self.grabber.urlgrab(self.progress.release.url, filename=filename, reget='simple')
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1172, in urlgrab
    return self._retry(opts, retryfunc, url, filename)
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1064, in _retry
    r = apply(func, (opts,) + args, {})
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1157, in retryfunc
    fo = PyCurlFileObject(url, filename, opts)
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1259, in __init__
    self._do_open()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1598, in _do_open
    self._set_opts()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1385, in _set_opts
    self.curl_obj.setopt(pycurl.NOPROGRESS, False)
pycurl.error: cannot invoke setopt() - perform() is currently running
Aborted
```

**Comment by kparal** [comment]
Another report: https://bugzilla.redhat.com/show_bug.cgi?id=1328340
