### ISSUE TITLE
Live USB broken on FC23

### ISSUE THREAD

**Issue by sjkeerthi** [lmacken/liveusb-creator#53]
liveusb-creator-3.95.2 

Traceback (most recent call last):
  File "/usr/bin/liveusb-creator", line 24, in <module>
    from liveusb import _
  File "/usr/lib/python2.7/site-packages/liveusb/**init**.py", line 54, in <module>
    from liveusb.creator import LinuxLiveUSBCreator as LiveUSBCreator
  File "/usr/lib/python2.7/site-packages/liveusb/creator.py", line 40, in <module>
    from liveusb.releases import releases
  File "/usr/lib/python2.7/site-packages/liveusb/releases.py", line 8, in <module>
    import grabber
  File "/usr/lib/python2.7/site-packages/liveusb/grabber.py", line 4, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/**init**.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning

**Comment by reypm** [comment]
Yeah, confirmed!! I am having the same issue in Fedora 24, could any take a look into this?

**Comment by rhnvrm** [comment]
Having the same issue on F24.

**Comment by Amitgb14** [comment]
Please upgrade request package.
`pip install --upgrade requests`

**Comment by sjkeerthi** [comment]
On fedora 24
liveusb-creator-3.95.4-1.fc24.noarch
liveusb-creator
Traceback (most recent call last):
  File "/usr/bin/liveusb-creator", line 24, in <module>
    from liveusb import _
  File "/usr/lib/python2.7/site-packages/liveusb/**init**.py", line 54, in <module>
    from liveusb.creator import LinuxLiveUSBCreator as LiveUSBCreator
  File "/usr/lib/python2.7/site-packages/liveusb/creator.py", line 40, in <module>
    from liveusb.releases import releases
  File "/usr/lib/python2.7/site-packages/liveusb/releases.py", line 8, in <module>
    import grabber
  File "/usr/lib/python2.7/site-packages/liveusb/grabber.py", line 4, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/**init**.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 22, in <module>
    from . import certs
ImportError: cannot import name certs
