### ISSUE TITLE
error when trying to run liveusb-creator on Arch Linux

### ISSUE THREAD

**Issue by SpEcHiDe** [lmacken/liveusb-creator#58]
```
[creator:996] extlinux not found! Only FAT filesystems will be supported
Traceback (most recent call last):
  File "/usr/bin/liveusb-creator", line 100, in <module>
    main()
  File "/usr/bin/liveusb-creator", line 91, in main
    LiveUSBApp(opts, sys.argv)
  File "/usr/lib/python2.7/site-packages/liveusb/gui.py", line 60, in __init__
    self.mywindow = LiveUSBWindow(opts, args)
  File "/usr/lib/python2.7/site-packages/liveusb/gui.py", line 291, in __init__
    self.populate_devices()
  File "/usr/lib/python2.7/site-packages/liveusb/gui.py", line 343, in populate_devices
    self.live.detect_removable_drives(callback=add_devices)
  File "/usr/lib/python2.7/site-packages/liveusb/creator.py", line 511, in detect_removable_drives
    "/org/freedesktop/UDisks")
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UDisks was not provided by any .service files
```

**Comment by ManuelSchmitzberger** [comment]
My solution on arch was to install the the `udisks-daemon`, which implements D-Bus interfaces used to query and manipulate storage devices.
https://wiki.archlinux.org/index.php/udisks
